name: Logger-App CI Workflow

on:
  push:
    branches: [ main ]

env:
  FRONTEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/logger-frontend-image
  BACKEND_IMAGE: ${{ secrets.DOCKER_USERNAME }}/logger-backend-image
  IMAGE_TAG: ${{ github.run_number }}

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      
      - name: Install pip
        run: |
          python -m ensurepip --upgrade
          python -m pip install --upgrade pip

      - name: Test Backend
        run: |
          cd backend
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          flake8 app.py
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Image Build
        run: |
          docker build -t $FRONTEND_IMAGE:$IMAGE_TAG -f frontend/Dockerfile frontend
          docker build -t $BACKEND_IMAGE:$IMAGE_TAG -f backend/Dockerfile backend

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Authenticate Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Image Scan
        run: |
          snyk container test $FRONTEND_IMAGE:$IMAGE_TAG --severity-threshold=critical --file=frontend/Dockerfile
          snyk container test $BACKEND_IMAGE:$IMAGE_TAG --severity-threshold=critical --file=backend/Dockerfile

      - name: Push to Registry
        run: 
